### ISSUE TITLE
Problems with circuit diagram

### ISSUE THREAD

**Issue by owhite** [rummanwaqar/teensy_can_example#2]
I think your diagram  is incorrect in the following ways:

1) Vdd should be connected to +5v
2) Vss should be connected to ground
3) the network for Vdd should connect to the teensy
4) the network for Vss should connect to the teensy

**Comment by rummanwaqar** [comment]
Thanks for creating the issue. You are right. Vdd and Vss were swapped. They are fixed now. As for not being connected to the teensy. This is not the full schematic for the system I was working on, so I didn't care to connect those. For proper functioning, you will be to do that.

**Comment by owhite** [comment]
thank you.
